
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 30 23:08:34 ICT 2018
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int INT = 8;
  public static final int DIVIDE = 6;
  public static final int BOOL = 11;
  public static final int SEMI = 2;
  public static final int EQUAL = 7;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int error = 1;
  public static final int TIMES = 5;
  public static final int CHAR = 10;
  public static final int FLOAT = 9;
}

